package com.itshare.exceptions.example1;

import java.nio.file.FileAlreadyExistsException;

public class Test {
	
	public static void main(String[] args) {
		
		
		int num1 = 10;
		int num2 =0;
		
	
		try {	
			System.out.println(num1/num2);
		}
		catch (ArrayIndexOutOfBoundsException fdadasde) {
			System.out.println(fdadasde.getMessage());
		}
	
		
		
		
		
		
		//System.out.println(num1/num2);

		
		
	}

}
